name: Pulumi Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Realizar checkout del repositorio en la raíz para evitar rutas duplicadas
      - uses: actions/checkout@v2

      # Mover al directorio correcto para todas las acciones subsecuentes
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: pulumi  # Esto asegura que npm instale en la carpeta correcta

      - name: Build TypeScript
        run: npm run build
        working-directory: pulumi  # Compila en la carpeta correcta

      - name: Login to Pulumi
        run: pulumi login --non-interactive --cloud-url https://api.pulumi.com
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: pulumi  # Cambia al directorio correcto antes de ejecutar el comando

      - name: Select Pulumi Stack
        run: pulumi stack select rodrilapenta/rog-ally-game-profiles/dev
        working-directory: pulumi  # Cambia al directorio correcto antes de ejecutar el comando
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up
        run: pulumi up --yes
        working-directory: pulumi  # Cambia al directorio correcto antes de ejecutar el comando
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}