name: Pulumi Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
        working-directory: pulumi
      - name: Build TypeScript
        run: npm run build  # Asegúrate de compilar TypeScript
        working-directory: pulumi
      - name: Login to Pulumi
        run: pulumi login --non-interactive --cloud-url https://api.pulumi.com
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: pulumi
      - name: Select Pulumi Stack
        run: pulumi stack select rodrilapenta/rog-ally-game-profiles/dev
        working-directory: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Pulumi Up
        run: npm run deploy  # Utiliza el script de deploy
        working-directory: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
